Add check if the git command is present

diff --git a/post-installation b/post-installation
--- a/post-installation
+++ b/post-installation
@@ -1,5 +1,12 @@
 #!/bin/sh
 
+# Check if the git command is available
+GIT=$(command -v git 2>/dev/null)
+if [ -z "$GIT" ]; then
+  echo "git: command not found. Aborting!"
+  exit 1
+fi
+
 ln -s ~/.vim/vimrc ~/.vimrc
 ln -s ~/.vim/gvimrc ~/.gvimrc
-git submodule update --init
+$GIT submodule update --init
diff --git a/update b/update
--- a/update
+++ b/update
@@ -1,3 +1,10 @@
 #!/bin/sh
 
-git pull origin master
+# Check if the git command is available
+GIT=$(command -v git 2>/dev/null)
+if [ -z "$GIT" ]; then
+  echo "git: command not found. Aborting!"
+  exit 1
+fi
+
+$GIT pull origin master
